version: '3.8'  # Убедитесь, что версия соответствует вашей среде Docker Compose

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Ссылка на глобально определенный том

volumes:
  redis_data:
    driver: local  # Определяем том глобально
