version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1  # Версия Zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"  # Пробрасываем порт для Zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.0.1  # Версия Kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Пробрасываем порт для Kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Ссылка на Zookeeper
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Используем localhost для доступа с хоста
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data  # Том для данных Kafka

volumes:
  kafka_data:
    driver: local  # Хранение данных Kafka
